# Generated by Django 3.2.15 on 2022-10-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_rename_information_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
